server {
    listen 80;
    server_name srv1287398.hstgr.cloud;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name srv1287398.hstgr.cloud;

    ssl_certificate /etc/letsencrypt/live/srv1287398.hstgr.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/srv1287398.hstgr.cloud/privkey.pem;

    root /var/www/inflexion-web;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    gzip on;
    gzip_types text/css application/javascript text/html;
}
